services:
  central-de-vagas-reporter-service:
    build:
      context: .
      target: dev-dependencies
      dockerfile: Dockerfile
    command: sh -c "bun install && bun run dev"
    container_name: central-de-vagas-reporter-service
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    working_dir: /app
    volumes:
      - .:/app
    env_file:
      - .env
