version: '3.7'

services:
  reporter_dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: default-route-openshift-image-registry.apps.ocpntx.defensoria.ro.def.br/central-vagas-dev/reporter:dev

  reporter_stage:
    build:
      context: .
      dockerfile: Dockerfile
    image: default-route-openshift-image-registry.apps.ocpntx.defensoria.ro.def.br/central-vagas-stage/reporter:stage

  reporter_prod:
    build:
      context: .
      dockerfile: Dockerfile
      # target: reporter
    image: default-route-openshift-image-registry.apps.ocpntx.defensoria.ro.def.br/central-vagas-prod/reporter:prod
