version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npm install && npm run start:dev"
    volumes:
      - .:/app
      - /app/node_modules
    working_dir: /app
    env_file:
      - .env
    ports:
      - '${API_PORT}:${API_PORT}'
    depends_on:
      - postgres
      - minio
    networks:
      - api-template-net

  postgres:
    image: docker.io/postgres:15
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '5432:5432'
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data:z
    networks:
      - api-template-net

  minio:
    image: docker.io/minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: '${MINIO_ACCESS_KEY}'
      MINIO_ROOT_PASSWORD: '${MINIO_SECRET_KEY}'
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./volumes/minio:/data:z
    networks:
      - api-template-net

networks:
  api-template-net:
    driver: bridge
