services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npm install && npm run build && npm run start:dev"
    volumes:
      - .:/code
      - /code/node_modules
    working_dir: /code
    env_file:
      - .env
    ports:
      - '${API_PORT}:${API_PORT}'
    depends_on:
      - postgres
      - minio
      - redis
    networks:
      - central-vagas-net

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npm install && npm run build && npm run start:worker"
    volumes:
      - .:/code
      - /code/node_modules
    working_dir: /code
    env_file:
      - .env
    environment:
      - WORKER_MODE=true
    depends_on:
      - postgres
      - redis
    networks:
      - central-vagas-net

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - ./volumes/redis:/data:z
    networks:
      - central-vagas-net

  postgres:
    image: docker.io/postgres:15
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '5432:5432'
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data:z
    networks:
      - central-vagas-net

  minio:
    image: docker.io/minio/minio
    command: server /data --console-address ":9001"

    environment:
      MINIO_ROOT_USER: 'teste'
      MINIO_ROOT_PASSWORD: 'Teste@123'
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./volumes/minio:/data:z
    networks:
      - central-vagas-net

networks:
  central-vagas-net:
    driver: bridge
